from typing import Any, Dict

def sw_cfg(bot) -> Dict[str, Any]: ...
def ensure_sw_cfg(bot) -> Dict[str, Any]: ...
def update_runtime_config(bot, guild, log_channel_id: int, responders_role) -> None: ...

