import discord
from typing import Optional
async def get_or_create_role(guild: discord.Guild, name: str) -> Optional[discord.Role]: ...
async def get_or_create_safe_category(guild: discord.Guild, name: str) -> Optional[discord.CategoryChannel]: ...
async def get_or_create_safe_channel(guild: discord.Guild, category: discord.CategoryChannel, name: str) -> Optional[discord.TextChannel]: ...

